#测试服
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#  spring.application.name=service-provider
#
#  spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'

redis:
  maxIdle: 16
  minIdle: 4
  maxWaitMillis: -1
  maxTotal: 16
  timeout: 0
  port: 6379
  host: 127.0.0.1