#本地
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greatcomingcloud?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: caonima
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  jmx:
#      enabled: false

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


