#测试服
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/mock?useSSL=false&verifyServerCertificate=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
     username: root
     password: 79839921
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

#  spring.application.name=service-provider
#
#  spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'

redis:
  maxIdle: 16
  minIdle: 4
  maxWaitMillis: -1
  maxTotal: 16
  timeout: 0
  port: 6379
  host: 127.0.0.1
