#测试环境配置
server:
  port: 8883
  servlet:
    context-path: /

spring:
  application:
    name: mock-factory-message-8883
  profiles:
      active: test


message:
  templateCode: SMS_183245926
  signName: MockFactory
